#! /bin/bash

MT="/tmp"
TD="$MT/AUSTAUSCH"

source /opt/AmutaQ!/etc/AmutaQ!.conf

mkdir $TD

if [ -d $TD ];then
    echo "Target available, fine!"
else
    echo "Target $TD NOT available, will mount!"
    mount $MT
fi

if [ -d $TD ];then
    echo "Target available, fine!"
else
    echo "Target $TD NOT available, exit!"
    exit 1
fi



DT=`date +"%d-%b-%y-%H"`
#FN="/opt/AmutaQ!/release_`hostname`${DT}.tar"
FN="/opt/AmutaQ!/release.tar"
FNT="/opt/AmutaQ!/release.txt"
FNI="/opt/AmutaQ!/release.inf"

echo "$VERSION" > $FNT
echo "`hostname`-${DT}" > $FNI

#rem diverse excludes
# tar --exclude="/opt/AmutaQ!/update" --exclude="*.0" --exclude="*.1" --exclude="*.2" --exclude="*.3" --exclude="/backup" --exclude="2015*" --exclude=*.idx --exclude="temp" --exclude="*.conf" --exclude="*.tmp" --exclude="*.txt" --exclude="*.tar" --exclude="test*" --exclude="bazaarvc*" -cf $FN /opt/AmutaQ!
tar -X ./mrelease.stt -cf $FN /opt/AmutaQ!
