#! /bin/bash

MT="/tmp"
TD="$MT/AUSTAUSCH"

mkdir $TD

if [ -d $TD ];then
    echo "Target available, fine!"
else
    echo "Target $TD NOT available, will mount!"
    mount $MT
fi

if [ -d $TD ];then
    echo "Target available, fine!"
else
    echo "Target $TD NOT available, exit!"
    exit 1
fi



DT=`date +"%d-%b-%y-%H"`
FN="/opt/AmutaQ!/release_`hostname`${DT}.tar"
#rem spoolfiles mit 2015 raus
tar --exclude="/opt/AmutaQ!/update" --exclude="*.0" --exclude="*.1" --exclude="2015*" --exclude=*.idx --exclude="temp" --exclude="*.conf" --exclude="*.tmp" --exclude="*.txt" --exclude="test*" --exclude="bazaarvc*" -cf $FN /opt/AmutaQ!

#exit

cp $FN "$TD/opt"
if [ $? -eq 0 ] ; then
    #rm $FN
    echo rm $FN
else
    echo "error in copy!"
fi
