#! /bin/bash
# monitoring lamw - in case that sshpass hangs
# by k.deiss@it-userdesk.de
# V 0.0.1
# V 0.0.3 14.2.20 mail output refined, less logging, improved script detection
# V 0.0.4 2.4.20 bugfix
# V 0.0.5.31.12.20 kd/ah bugfix detecting process already running
# V 0.0.6.9.1.23 kd bugfix detecting process already running (looking for ghettoVCB.sh if not it will kill a running restore!)

source /opt/AmutaQ!/etc/AmutaQ!.conf

LOG="/var/log/control_lamw.log"
TMP="/tmp/$$.tmp"
MTMP="/tmp/$$_mail.tmp"
BAZAARLOGDIR="/tmp"
BAZAARLOGFN="lamw.log"

source /opt/AmutaQ!/lib/mail.lib

##############script detection#########################
LOCKFILE=/tmp/$(basename $0).lck
#[ -f $LOCKFILE ] && { echo "`date` INF $0 already running" >> $LOG; exit 1; }
if [ -f $LOCKFILE ] ; then
    SPID=`cat $LOCKFILE`
#    ps -e | grep $SPID >> /dev/null
    ps -o cmd -p $SPID |grep `basename $0` >> /dev/null
    if [ $? -eq 0 ] ; then
        echo "`date` INF $0 already running with $SPID" >> $LOG
        exit 1
    else
        echo "" >> $LOG
        echo "`date` WAR $0 has lockfile but is not running!" >> $LOG
    fi
fi



del_lock()
{
    #echo "`date` $0 WARNING external signal caught, exiting" >> $LOG
    rm -f $TMP
    rm -f $MTMP
    rm -f $LOCKFILE
}

trap "del_lock ; exit 1" 2 9 15
echo $$ > $LOCKFILE
##############script detection#########################


PIDB=`pidof sshpass`
if [ -z $PIDB ];then
    #echo "`date` sshpass not running - lamw not active" >> $LOG
    del_lock
    exit 0
else
    PSX=`ps aux | grep sshpass |grep ghettoVCB.sh`
    if [ ! -z "$PSX" ] ; then
        echo "`date` sshpass running - lamw seems to be active ==> $PSX" >> $LOG
    else
        #there is an sshpass running on this machine but not for ghetto
        echo "`date` sshpass running - but not ours ==> $PSX" >> $LOG
        del_lock
        exit 0
    fi
fi


RST=`find $BAZAARLOGDIR -type f -mmin "+59" -name $BAZAARLOGFN`
if [ ! -z $RST ] ; then
    echo "`date` lamw seems to hung - logfile older 59 min - killing sshpass!" >> $LOG
    ls -la $BAZAARLOGDIR/$BAZAARLOGFN >> $LOG
    cat $BAZAARLOGDIR/$BAZAARLOGFN >> $LOG
    echo "`date` will kill now sshpass" >> $LOG
    killall -9 sshpass >> $LOG
    sleep 10
    killall -9 sshpass >> $LOG
    sleep 10
else
    echo "`date` lamw logfile not old enough!"
    del_lock
    exit 0
fi

cat $BAZAARLOGDIR/$BAZAARLOGFN >> $MTMP
PIDB=`pidof sshpass`
if [ ! -z $PIDB ];then
    echo "`date` ooops task still running - something went wrong!" >> $LOG
    SUBJECT="`hostname` lamw hanging!"
    echo "$SUBJECT \n\n${VERSION}\n\nNot able to kill hanging service.\n\nPlease restart this machine.\n\n" > $MTMP
    cat $BAZAARLOGDIR/$BAZAARLOGFN >> $MTMP
    TXTFILE=$MTMP
    #TXT="$SUBJECT \n\n${VERSION}\n\nNot able to kill hanging service.\n\nPlease restart this machine."
    TXT=""
    send_mail
    sleep 1800
else
    SUBJECT="`hostname` lamw hanging!"
    echo "$SUBJECT \n\n${VERSION}\n\nLAMW backup was hanging.\n\nThe hanging task has been killed successfully.\n\n" > $MTMP
    cat $BAZAARLOGDIR/$BAZAARLOGFN >> $MTMP
    TXTFILE=$MTMP
    #TXT="$SUBJECT \n\n${VERSION}\n\nLAMW backup was hanging.\n\nThe hanging task has been killed successfully."
    TXT=""
    send_mail
fi

del_lock
