#! /bin/bash
# by k.deiss@it-userdesk.de
# webmin interface - which device could be removed
# V 0.0.1 29.9.14
# V 0.0.2 29.12.15 trans-discnames ausgelagert in LIB
# V 0.0.3 1.3.17 bugfix


# don't edit from here

source /opt/AmutaQ!/etc/AmutaQ!.conf
source /opt/AmutaQ!/lib/discident.lib
# usage echo "HDD `trans-discnames $i` could be removed."


DDUMB=`mount | grep ddumbfs`
let UMOUNT=2


echo "HDD `trans-discnames $1` could be removed."



function getMachineSpecificValues()
{
fn="/opt/AmutaQ!/etc/$VMGUEST.conf"

if [ -f $fn ] ;then
    source $fn
    echo  "`date` INF DONTRUNFROM: $DONTRUNFROM"
    echo  "`date` INF DONTRUNTILL: $DONTRUNTILL"
    echo  "`date` INF BAZAAREXTRAPARMS: $BAZAAREXTRAPARMS"

    if [ -z $ALLOWREBOOT ] ; then
	echo  "`date` INF adding new PARM ALLOWREBOOT=0 to $fn"
	echo "let ALLOWREBOOT=0" >>$fn
	let ALLOWREBOOT=0
    fi
    echo  "`date` INF ALLOWREBOOT: $ALLOWREBOOT"
else
    let DONTRUNTILL=-1
    let DONTRUNFROM=24
    BAZAAREXTRAPARMS=""
    echo "let DONTRUNFROM=24" >>$fn
    echo "let DONTRUNTILL=-1" >>$fn
    echo "BAZAAREXTRAPARMS=" >>$fn
    echo "let ALLOWREBOOT=0" >>$fn
    echo  "`date` INF creating machine specific config: $fn"
fi
}

VMGUEST="dose22"
getMachineSpecificValues
