#! /bin/bash

#######################don't edit from here ########################

source /opt/AmutaQ!/etc/AmutaQ!.conf

LOG="/var/log/migrate_fs.log"
source /opt/AmutaQ!/lib/mail.lib

ERRTMP="/tmp/mount_fs_$$.tmp"
LASTDEVICE="/tmp/current_backup_vol"

RECLAIM="/opt/AmutaQ!/ddumbfs/reclaim"
BACKUP2DDUMB="/opt/AmutaQ!/backup/backup2ddumb"
INDEXDIR="/opt/AmutaQ!/indexfiles"
let ONLYMOUNT=0
let FORCECHECK=0

DDUMBVOL="/mnt/ddumbfs1"

date > $LOG

if [ ! -z "$1" ];then
    TARGETHD=$1
    echo  "Targetdevice got from commandline: $1" | tee -a $LOG
    mount | grep "/mnt/$TARGETHD" 2> /dev/null > /dev/null
    if [ $? -eq 0 ] ; then
	echo "$TARGETHD already mounted" | tee -a $LOG
    else
	mount /mnt/$TARGETHD 2> /dev/null > /dev/null
	if [ $? -eq 0 ] ; then
	    echo "$TARGETHD mounted successfully!" | tee -a $LOG
	else
	    echo "Can't mount $TARGETHD - exit !" | tee -a $LOG
	    exit 1
	fi
    fi

else
    echo  "No targetgetdevice got from commandline: $1 - exit" | tee -a $LOG
    exit 1
fi


/usr/local/bin/migrateddumbfs -m -f -v -p /mnt/$TARGETHD/l0/ddumbfs /mnt/$TARGETHD/l0.new/ddumbfs | tee -a $LOG
