#! /bin/bash
# by k.deiss@it-userdesk.de
# V 0.0.1.05.05.17 initial release
# V 0.0.2.31.12.20 kd/ah bugfix detecting process already running


source /opt/AmutaQ!/etc/AmutaQ!.conf
LOG="/var/log/syncftp.log"


##############script detection#########################
LOCKFILE=/tmp/$(basename $0).lck

if [ -f $LOCKFILE ] ; then
    SPID=`cat $LOCKFILE`
#    ps -e | grep $SPID >> /dev/null
    ps -o cmd -p $SPID |grep `basename $0` >> /dev/null
    if [ $? -eq 0 ] ; then
	echo "`date` INF $0 already running"
	exit 1
    else
	echo "`date` WAR $0 has lockfile but is not running!" >> $LOG
    fi
fi


del_lock()
{
    echo "`date` WAR $0 external signal caught, exiting $0)." >> $LOG
    rm -f $LOCKFILE
}

trap "del_lock ; exit 1" 2 9 15
echo $$ > $LOCKFILE
##############script detection#########################

echo "" >> $LOG
echo "`date` INF $0 PID:$$ startup" >> $LOG
$0-aux $1 2>&1 | tee -a $LOG
echo "`date` INF $0 PID:$$ shutdown" >> $LOG
rm -f $LOCKFILE
