#! /bin/bash
# decode and mount bufferdisk
# V 0.0.1.12.9.19 luks beta

UUID=`cat /etc/crypttab |grep "bufferdisk " | cut -d= -f2 | cut -d" " -f1`
cryptsetup luksOpen --disable-keyring /dev/disk/by-uuid/$UUID bufferdisk
mount /mnt/bufferdisk
#cryptsetup luksOpen /opt/AmutaQ!/crypt_indexfiles indexfiles --key-file=/mnt/bufferdisk/.crypt/key_indexfiles
#cryptdisks_start indexfiles
#mount /opt/AmutaQ!/indexfiles
