#! /bin/bash
# decode and mount bufferdisk
# V 0.0.1.12.9.19 luks beta
# V 0.0.2.10.12.20 restart NFS-Server after all
# V 0.0.3.12.11.21 bugfix mounting crypted Bufferdisk

UUID=`cat /etc/crypttab |grep "bufferdisk " | cut -d= -f2 | cut -d" " -f1`

if [ -f /mnt/bufferdisk/bazaar/NOT_MOUNTED ]; then
        echo .
        echo "Bufferdisk is not mounted. Please enter password"
	sudo cryptsetup luksOpen --disable-keyring /dev/disk/by-uuid/$UUID bufferdisk
	sudo mount /mnt/bufferdisk
	sudo service nfs-kernel-server restart
fi
