#! /bin/bash
# by k.deiss@it-userdesk.de
# acces every esxi host and write a testsquence to bufferdisk
# V 0.0.1 19.7.18



#don't edit from here


source /opt/AmutaQ!/etc/AmutaQ!.conf

/opt/AmutaQ!/lamw/vm_restore_single /tmp/lamw_restore.conf 192.168.19.14 1
