#! /bin/bash
# by k.deiss@it-userdesk.de
# restore of single machine with w.lam script (ghettoVCB)

# V 0.0.1 31.12.22


#don't edit from here

CONFIG="/opt/AmutaQ!/etc/AmutaQ!.conf"
#source $CONFIG


LOG="/var/log/amu_restore.log"
BASEPATH="/opt/AmutaQ!/lamw"
LAMWLOG="/var/log/lamw_restore.log"
TMPLOG="/tmp/lamw_restore.log"

FNAMEA="ghettoVCB-restore-from-amutaq.sh"
FNAMEB="ghettoVCB-restore.sh"

# The commandline to the ESXI host
#CMDL="sshpass -p "$VMPASSWORD" ssh -o StrictHostKeyChecking=no $VMUSER@$VMHOST"
CMDL=""

PF=`hostname`


##############script detection#########################
LOCKFILE=/tmp/$(basename $0).lck

if [ -f $LOCKFILE ] ; then
    SPID=`cat $LOCKFILE`
#    ps -e | grep $SPID >> /dev/null
    ps -o cmd -p $SPID |grep `basename $0` >> /dev/null
    if [ $? -eq 0 ] ; then
	echo "`date` INF $0 already running!"
	exit 1
    else
	echo "`date` WAR $0 has lockfile but is not running!"
    fi
fi


del_lock()
{
    echo "`date` WAR $0 external signal caught, exiting" 
    echo "`date` WAR compatibility logfile end - $0 external signal caught, exiting" >> $LAMWLOG
    rm -f $LOCKFILE
}

trap "del_lock ; exit 1" 2 9 15
echo $$ > $LOCKFILE
##############script detection#########################



#we run the lamw scripts on the ESXi host
run_restore()
{
cf=`basename $CONFIGFILE`
echo -n "" > $TMPLOG
$CMDL "chmod 777 /tmp/${PF}_restore/$FNAMEA"
$CMDL "chmod 777 /tmp/${PF}_restore/$FNAMEB"

#echo $CMDL "/tmp/${PF}_restore/$FNAMEA -c /tmp/${PF}_restore/$cf"

if [ $RESTOREMODE -eq 0 ] ;then
    #just link the files
    echo "`date` INF restoring vm guests with linked files."
    $CMDL "/tmp/${PF}_restore/$FNAMEA -c /tmp/${PF}_restore/$cf" 2>> $LAMWLOG | tee -a $TMPLOG
    RST=$?
    cat $TMPLOG >> $LAMWLOG
    return $RST
fi

if [ $RESTOREMODE -eq 1 ] ;then
    #copy the files into esxi host
    echo "`date` INF restoring vm guests copy files to ESXi host."
    $CMDL "/tmp/${PF}_restore/$FNAMEB -c /tmp/${PF}_restore/$cf" 2>> $LAMWLOG | tee -a $TMPLOG
    cat $TMPLOG >> $LAMWLOG
    RST=$?
    cat $TMPLOG >> $LAMWLOG
    return $RST
fi

echo "`date` ERR can't invalid restore mode"
return 10
}




#we copy the lamw scripts to the ESXi host
copy_files()
{
# /tmp folder of esxi host
$CMDL "rm -f /tmp/${PF}_restore/lamw_workdir/* 2>/dev/null"
$CMDL "rmdir /tmp/${PF}_restore/lamw_workdir 2>/dev/null"
$CMDL "rm -f /tmp/${PF}_restore/* 2>/dev/null"
$CMDL "rmdir /tmp/${PF}_restore"

$CMDL "mkdir /tmp/${PF}_restore"

fname="$BASEPATH/$FNAMEA"
sshpass -p "$VMPASSWORD" scp "$fname" "root@$TARGETSERVER:/tmp/${PF}_restore"
if [ ! $? -eq 0 ];then
    echo "`date` ERR can't copy $fname to ESXi Host $TARGETSERVER"
    return 1
fi

fname="$BASEPATH/$FNAMEB"
sshpass -p "$VMPASSWORD" scp "$fname" "root@$TARGETSERVER:/tmp/${PF}_restore"
if [ ! $? -eq 0 ];then
    echo "`date` ERR can't copy $fname to ESXi Host $TARGETSERVER"
    return 1
fi

fname="$CONFIGFILE"
sshpass -p "$VMPASSWORD" scp "$fname" "root@$TARGETSERVER:/tmp/${PF}_restore"
if [ ! $? -eq 0 ];then
    echo "`date` ERR can't copy $fname to ESXi Host $TARGETSERVER"
    return 1
fi


return 0
}






##########################################################
#			MAIN
##########################################################

echo "`date` INF startup $0 $1 $2 $3"

WARMSG="usage $0 CONFIGFILE TARGETSERVER RESTOREMODE(0=LINK,1=COPY) [PASSWORD]"


CONFIGFILE=$1
if [ -z $CONFIGFILE ] ; then
    echo $WARMSG
    rm -f $LOCKFILE
    exit 1
fi

if [ ! -f $CONFIGFILE ];then
    echo $WARMSG
    rm -f $LOCKFILE
    exit 2
fi

TARGETSERVER=$2
if [ -z $TARGETSERVER ] ; then
    echo $WARMSG
    rm -f $LOCKFILE
    exit 1
fi

RESTOREMODE=$3
if [ -z $RESTOREMODE ] ; then
    echo $WARMSG
    rm -f $LOCKFILE
    exit 1
fi

VMPASSWORD=$4
if [ ! -z $VMPASSWORD ] ; then
    echo "`date` INF password received from commandline!"
fi


#echo "$CONFIGFILE $TARGETSERVER"

#we have to find the config file and extract pw for the targetserver if it is not given by commandline
if [ -z "$VMPASSWORD" ];then
if [ -f $CONFIG.0 ];then 
    let f=0
    while [ $f -lt 100 ];do
	if [ -f $CONFIG.$f ];then
	    #echo $CMDL
	    source "$CONFIG.$f"
	    if [ " $VMHOST" == " $TARGETSERVER" ];then
		echo "Config for $TARGETSERVER found in $CONFIG.$f!"
		CMDL="sshpass -p "$VMPASSWORD" ssh -o StrictHostKeyChecking=no $VMUSER@$VMHOST"
	    fi
	else
	    break
	fi
	let f=$f+1
    done
else
    if [ -f $CONFIG ];then 
	source "$CONFIG.$f"
	if [ " $VMHOST" == " $TARGETSERVER" ];then
	    echo "Config for $TARGETSERVER found in $CONFIG"
	    CMDL="sshpass -p "$VMPASSWORD" ssh -o StrictHostKeyChecking=no $VMUSER@$VMHOST"
	fi
    fi
fi
else
    CMDL="sshpass -p "$VMPASSWORD" ssh -o StrictHostKeyChecking=no root@$TARGETSERVER"
fi

#echo $CMDL
if [ -z "$CMDL" ];then
    echo "`date` ERR can't find configuration for host $TARGETSERVER - call $0 with password"
    rm -f $LOCKFILE
    exit 1
fi

copy_files
if [ ! $? -eq 0 ] ; then
    echo "`date` ERR can't copy script/config to host $TARGETSERVER"
    rm -f $LOCKFILE
    exit 1
fi

run_restore



echo "`date` INF terminating $0"
rm -f $LOCKFILE
